transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 5.0

global_frame: map
robot_base_frame: base_footprint
resolution: 0.05

rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}
  - {name: sensor,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}

static:
  map_topic: /map
  subscribe_to_updates: true

explore_boundary:
  resize_to_boundary: false
  frontier_travel_point: middle
  explore_clear_space: false

sensor:
  observation_sources: scan
  scan: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}


inflation:
  inflation_radius: 0.15