global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0 # 10.0
  publish_frequency: 10.0 #10.0
  transform_tolerance: 2.0 #0.75 #0.5
  #footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
  robot_radius: 0.20
  inflation_radius: 0.15 #0.4 #0.3 0.2
  cost_scaling_factor: 6.0 #75
  static_map: true
